-- Durable plan-first AI thread scheduling. These are owned by the ai-user
-- orchestrator, so they intentionally use the ai-user Flyway history table.

CREATE TABLE IF NOT EXISTS ai_thread_plans (
    id                          VARCHAR(36)  NOT NULL,
    post_id                     VARCHAR(32)  NOT NULL,
    post_revision               INT          NOT NULL,
    source_type                 VARCHAR(16)  NOT NULL COMMENT 'AI_POST|HUMAN_POST',
    status                      VARCHAR(16)  NOT NULL,
    provider                    VARCHAR(16)  NULL,
    model                       VARCHAR(64)  NULL,
    content_hash                CHAR(64)     NULL,
    source_title                VARCHAR(255) NULL,
    source_body                 LONGTEXT     NULL,
    source_category             VARCHAR(32)  NULL,
    published_at                DATETIME(3)  NULL,
    absolute_expires_at         DATETIME(3)  NOT NULL,
    effective_exposure_seconds  BIGINT       NOT NULL DEFAULT 0,
    exposure_calculated_at      DATETIME(3)  NULL,
    generation_attempts         INT          NOT NULL DEFAULT 0,
    failure_code                VARCHAR(64)  NULL,
    created_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_thread_plan_post_revision (post_id, post_revision),
    KEY idx_thread_plan_status_expiry (status, absolute_expires_at),
    KEY idx_thread_plan_post (post_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_thread_plan_items (
    id                          VARCHAR(36)  NOT NULL,
    plan_id                     VARCHAR(36)  NOT NULL,
    item_type                   VARCHAR(20)  NOT NULL,
    status                      VARCHAR(16)  NOT NULL,
    sequence_no                 INT          NOT NULL,
    parent_item_id              VARCHAR(36)  NULL,
    persona_id                  VARCHAR(32)  NULL,
    target_post_id              VARCHAR(32)  NOT NULL,
    target_comment_id           VARCHAR(64)  NULL,
    body                        LONGTEXT     NULL,
    scheduled_at                DATETIME(3)  NULL,
    not_before                  DATETIME(3)  NULL,
    idempotency_key             VARCHAR(128) NOT NULL,
    lease_owner                 VARCHAR(64)  NULL,
    lease_until                 DATETIME(3)  NULL,
    attempt_count               INT          NOT NULL DEFAULT 0,
    failure_code                VARCHAR(64)  NULL,
    posted_target_id            VARCHAR(64)  NULL,
    created_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_thread_plan_item_idempotency (idempotency_key),
    KEY idx_thread_plan_item_due (status, scheduled_at, not_before),
    KEY idx_thread_plan_item_lease (status, lease_until),
    KEY idx_thread_plan_item_plan (plan_id, sequence_no),
    KEY idx_thread_plan_item_parent (parent_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_human_interaction_inbox (
    id                          VARCHAR(36)  NOT NULL,
    post_id                     VARCHAR(32)  NOT NULL,
    source_comment_id           VARCHAR(64)  NOT NULL,
    parent_comment_id           VARCHAR(64)  NULL,
    author_id                   VARCHAR(32)  NOT NULL,
    interaction_type            VARCHAR(16)  NOT NULL COMMENT 'COMMENT|REPLY',
    status                      VARCHAR(16)  NOT NULL,
    observed_at                 DATETIME(3)  NOT NULL,
    expires_at                  DATETIME(3)  NOT NULL,
    lease_owner                 VARCHAR(64)  NULL,
    lease_until                 DATETIME(3)  NULL,
    response_item_id            VARCHAR(36)  NULL,
    failure_code                VARCHAR(64)  NULL,
    created_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_human_inbox_source_comment (source_comment_id),
    KEY idx_human_inbox_batch (status, observed_at, expires_at),
    KEY idx_human_inbox_lease (status, lease_until),
    KEY idx_human_inbox_post (post_id, observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
