CREATE TABLE system_setting (
  setting_key   VARCHAR(100) NOT NULL PRIMARY KEY,
  setting_value TEXT,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by    VARCHAR(100)
);
