from .sc_v10_guest_limit import SCENARIO_SC_V10_GUEST_LIMIT
from .sc_v10_daily_limit import SCENARIO_SC_V10_DAILY_LIMIT
from .sc_v10_feedback import SCENARIO_SC_V10_FEEDBACK
from .sc_v10_crisis_resource import SCENARIO_SC_V10_CRISIS_RESOURCE
from .sc_v10_beta_banner import SCENARIO_SC_V10_BETA_BANNER
from .sc_v10_admin_access import SCENARIO_SC_V10_ADMIN_ACCESS
from .sc_v10_user_deletion import SCENARIO_SC_V10_USER_DELETION

ALL_V10_SCENARIOS = [
    SCENARIO_SC_V10_GUEST_LIMIT,
    SCENARIO_SC_V10_DAILY_LIMIT,
    SCENARIO_SC_V10_FEEDBACK,
    SCENARIO_SC_V10_CRISIS_RESOURCE,
    SCENARIO_SC_V10_BETA_BANNER,
    SCENARIO_SC_V10_ADMIN_ACCESS,
    SCENARIO_SC_V10_USER_DELETION,
]
